### ISSUE TITLE
Pkg25.add()

### ISSUE THREAD

**Issue by geauxdojang** [KristofferC/Pkg25.jl#1]
@KristofferC :  Can you explain this step (bold part) to install and use Pkg25 to add packages? Thanks.

> Add using Pkg25; **const Pkg = Pkg25 to .juliarc.jl.**

**Comment by KristofferC** [comment]
Open .juliarc.jl (in your home folder). 
Paste "using Pkg25; const Pkg = Pkg25" in there. 
Start julia.

**Comment by geauxdojang** [comment]
@KristofferC : By home folder, do you mean a folder where I clone Pkg25? If yes, I do not see .juliarc.jl file in it. 
Thanks.

**Comment by KristofferC** [comment]
On Windows it should be in the folder just above the `.julia` directory.

**Comment by geauxdojang** [comment]
@KristofferC : I found the location and pasted "using Pkg25; const Pkg = Pkg25" in .juliarc.jl file (both with and without quotes). But, Julia never ran and closed as I started it up. Thanks.

**Comment by KristofferC** [comment]
Did you do the `Manually clone this repo into ~/.julia/v0.x/Pkg25` step?

**Comment by geauxdojang** [comment]
@KristofferC : Yes, I cloned it and saved it in ~v0.5\Pkg25\Pkg25.jl. Thanks.

**Comment by geauxdojang** [comment]
@KristofferC : Any idea why it is not working? Thanks.

**Comment by KristofferC** [comment]
Does just `using Pkg25` in the REPL work?

**Comment by geauxdojang** [comment]
No. Thanks.

**Comment by KristofferC** [comment]
Can you start Julia and do `Pkg.clone("https://github.com/KristofferC/Pkg25.jl")`.

**Comment by geauxdojang** [comment]
OK. I did it. Now, Do I paste the using Pkg25; const Pkg = Pkg25 in .juliarc.jl?

**Comment by KristofferC** [comment]
Yes

**Comment by geauxdojang** [comment]
OK. This time, after I pasted Pkg25; const Pkg = Pkg25 in .juliarc.jl, Julia started fine. However, the `Pkg.add()` is still too slow and is same as before. Thanks.

**Comment by KristofferC** [comment]
Ok, to make sure, when you start julia and type `Pkg` it says `Pkg25` as the output?

In that case go to your `.julia/v0.5` folder, delete the METADATA folder, start julia and run `Pkg.init()`. Please paste the output here.

**Comment by geauxdojang** [comment]
OK. I do not see METADATA folder in `.julia/v0.5`. I did what you said and below is the output.

![image](https://cloud.githubusercontent.com/assets/9141145/24219611/6b0c4554-0f15-11e7-9e65-e47bf629350a.png)

**Comment by KristofferC** [comment]
Run `Pkg.dir()`. There should be a `METADATA` folder in there.

**Comment by geauxdojang** [comment]
@KristofferC : Thanks. This is working now. How is the expected speed boost? I got intermittent Pkg25 error also.

![image](https://cloud.githubusercontent.com/assets/9141145/24220442/3dca2a86-0f18-11e7-8848-df29fa86a2af.png)

**Comment by KristofferC** [comment]
I have just tried this on a cluster and it was significantly faster there. You will have to test the performance yourself. I have not seen that error before and unfortunately, I don't have much time to put on this issue.

**Comment by geauxdojang** [comment]
OK, Thanks. I am closing this issue. Thanks a lot for your time.

**Comment by KristofferC** [comment]
No problems. Just so you know, work is being done on a new package system which is designed to not hit the filesystem so hard as the current one and should thereby be much faster on slow filesystems. Unfortunately it will take some time to be finished...

**Comment by geauxdojang** [comment]
OK. Thanks.
